# Generated by Django 5.2 on 2025-05-01 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="is_complete",
            new_name="is_completed",
        ),
    ]
